sudo: required
dist: trusty

language: cpp

compiler:
    - gcc

script: ci/bin/test

deploy:
#  provider: s3
#  bucket: usf-hii-madeline-ci
#  local-dir: ci/tmp
#  on:
#    repo: piratical/Madeline_2.0_PDE
#    branch: master
#  skip_cleanup: true
#  access_key_id: 
#  secret_access_key:
#    secure: 
